### ISSUE TITLE
[Suggestion] Add level-scaling to mmoitems

### ISSUE THREAD

**Issue by Storexo** [Seyarada/PandeLootPlus#2]
When a MythicMob dies, add the ability to scale the item level to the level of the MythicMob. 

For example, the player kills a level 16 MythicMob, -> generate an item with that specific item level. 

Been requesting it on MMOItems side for a while now without success, so figured it might be possible with this plugin!

Otherwise amazing plugin, keep it up!

**Comment by Seyarada** [comment]
Added support for this in the most recent version, had to move a lot of stuff around so it's a bit experiemental but worked fine from my testing

To use it use the <caster.level> placeholder as a MI Type flag attribute, here's an example
%rs% and %ls% are placeholders for < & > respectively

```yml
TestPandeLoot:
  Type: Pig
  Health: 1
  AIGoalSelectors:
  - clear
  Skills:
  - setlevel{l=1000} @self ~onSpawn
  Rewards:
  - mi:SOULSTEALER{type=SWORD <level=%rs%caster.level%ls%>}
```
